language: none
sudo: required

services:
- docker
- docker-compose

branches:
  only:
  - /.*/

before_script: 
- cd deploy
- echo $TRAVIS_COMMIT
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD

script:
  if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=dev;  fi; tag=$TRAVIS_TAG docker-compose build

deploy:
- provider: script
  script:
      - docker login --help 
      - echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin 
      - docker push onyxpay/onyxpay:$TRAVIS_TAG
      
  on:
    tags: true 
    condition: $TRAVIS_TAG =~ ^prod|preprod$
